### ISSUE TITLE
[amqp1] Create loop to parse and generate Instances

### ISSUE THREAD

**Issue by leifmadsen** [infrawatch/collectd-config-ansible-role#6]
https://github.com/infrawatch/collectd-config-ansible-role/blob/ff4645f1143d77d8314604483db25769407f3dc5/templates/amqp1.conf.j2#L6-L22

**Comment by elfiesmelfie** [comment]
For future reference (whoever, maybe me, that addresses this issue): the template will look similar to what is in [ceph](https://github.com/infrawatch/collectd-config-ansible-role/blob/ff4645f1143d77d8314604483db25769407f3dc5/templates/ceph.conf.j2#L10-L13)
